### ISSUE TITLE
I receive a message as consumer, but the string arrives with some noise

### ISSUE THREAD

**Issue by juamarCas** [CopernicaMarketingSoftware/AMQP-CPP#439] opened 2021-11-25 13:43 UTC
My System OS is Ubuntu 20.04

I created the following message C++ producer script modifying the example in the documentation to send a message to a C++ consumer
```C++
#include "MyHandler.h"

int main()
{
   auto *loop = EV_DEFAULT;
   MyHandler myHandler(loop);
   AMQP::Address address("amqp://guest:guest@localhost/");
   AMQP::TcpConnection connection(&myHandler, address);

   AMQP::TcpChannel channel(&connection);
   channel.declareQueue("myqueue").onSuccess([&channel](const std::string &name, uint32_t messageCount, uint32_t consumercount){
            std::cout<<"declared queue: myqueue"<<std::endl;
            while(1){
               std::string msg; 
               std::cout<<"type a message: "<<std::endl;
               std::getline(std::cin, msg);  
               channel.publish("", "myqueue", msg); 
            }
   });


   ev_run(loop);

   return 0;

}
```

where "MyHandler.h" is just a header file with the MyLibEv Handler class.

and the following consumer script: 
```C++
#include "MyHandler.h"

int main()
{
   auto *loop = EV_DEFAULT;
   MyHandler myHandler(loop);
   AMQP::Address address("amqp://guest:guest@localhost/");
   AMQP::TcpConnection connection(&myHandler, address);

   AMQP::TcpChannel channel(&connection);
   channel.declareQueue("myqueue").onSuccess([&channel](const std::string &name, uint32_t messageCount, uint32_t consumercount){
            std::cout<<"declared queue"<<std::endl;
   });

   // callback function that is called when the consume operation starts
auto startCb = [](const std::string &consumertag) {

    std::cout << "consume operation started" << std::endl;
};

// callback function that is called when the consume operation failed
auto errorCb = [](const char *message) {

    std::cout << "consume operation failed" << std::endl;
};

// callback operation when a message was received
auto messageCb = [&channel](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered) {

    std::cout << "message received:" << std::endl;
    std::cout << message.body()<<std::endl;    
    channel.ack(deliveryTag);
};

channel.consume("myqueue")
       .onReceived(messageCb)
       .onSuccess(startCb)
       .onError(errorCb);

   ev_run(loop);

   return 0;

}
```

So, almost everything is fine, but, whenever I send a message with the producer as follows while running the code: 

```
ready
declared queue: myqueue
type a message: 
hello there
type a message: 
my name is juanito
type a message: 
```

with the consumer I receive: 
```
ready
declared queue
consume operation started
message received:
hello there�
message received:
my name is juanito�BJ-99rYBl3wNkbJSQ

```

With some noise, I tried with node consumer and it prints the message perfectly.

Thank you.

**Comment by rwols** [comment] 2021-11-25 13:46
The body is not null-terminated. Use something like a string_view to make std::cout understand that:

```cpp
std::cout << std::string_view{message.body(), message.bodySize()} <<std::endl;
```

**Comment by rwols** [comment] 2021-11-25 13:50
duplicate of https://github.com/CopernicaMarketingSoftware/AMQP-CPP/issues/383

**Closed by rwols** 2021-11-25 13:50 UTC
