### ISSUE TITLE
Fix non-Linux build for recent commit.

### ISSUE THREAD

**Issue by surgura** [CopernicaMarketingSoftware/AMQP-CPP#176] opened 2018-01-30 12:38 UTC
@Aljar @EmielBruijntjes 

Commit c2873827707146a9e5df1517378be43e5d22a16a breaks the non-Linux build again which was fixed in 91c4f891590c630df4f2a18e3f5925ddf41b3d3f.

The cause:
``` C++
// include/amqpcpp.h
// tcp level includes
#include "amqpcpp/tcphandler.h"
#include "amqpcpp/tcpconnection.h"
#include "amqpcpp/tcpchannel.h"
````

This has been added because programs using AMQP-CPP failed to build if they depend of the TCP module. The TCP module is however not compatible outside of Linux. We cannot have these files included in `include/amqpcpp.h`.

Instead, to fix your Linux build you need to include `include/linux_tcp.h` next to `include/amqpcpp.h`.

If you use either `libboostasio.h`, `libev.h`, `libevent.h`, or `libuv.h` you are indirectly dependent on the TCP module. These files will include `include/linux_tcp.h` for you as of #173, so you don't have to do anything but update after that has been merged.

**Comment by zerodefect** [comment] 2018-01-30 13:09
The sooner we get AppVeyor/Travis-ci building the examples (not just the lib), the better. It will hopefully catch the majority of these issues before they enter the repo.

**Comment by lazedo** [comment] 2018-01-30 13:43
@surgura i think the problem is that your recent changes made the build not work as it used to be for linux. you changed the behavior of the build system by setting the build tcp linux to `OFF` by default when it should have been `ON` for keeping it working as it was

**Comment by EmielBruijntjes** [comment] 2018-01-30 13:58
I understand what you did, but half of our code suddenly failed to compile after the recent changes and a lot of screens turned red here. So I changed it back for the time being to make everybody happy again. Will be fixed later on.

**Comment by surgura** [comment] 2018-01-30 14:23
@EmielBruijntjes I understand the reasoning behind the quickfix. I will wait for an update from your side and hope we can soon remove the quickfix in one way or another.

**Comment by EmielBruijntjes** [comment] 2018-03-08 21:41
This has been fixed.

**Closed by EmielBruijntjes** 2018-03-08 21:41 UTC

**Comment by surgura** [comment] 2018-03-08 23:29
Sweet
