### ISSUE TITLE
declareQueue report Success before OnSuccess callback is installed.

### ISSUE THREAD

**Issue by liushiqi9** [CopernicaMarketingSoftware/AMQP-CPP#414] opened 2021-08-03 11:41 UTC
LibraryVersion: 4.3.14
Hi
Using demo program in example, and connecting to a rabbitmq on localhost, I found out that running code below, both OnSuccess and OnError might never get called. 

I look inside AMQP-CPP and found  out that in channelimpl.h, function reportSuccess is called with _oldestCallback== nullptr, and only after that the OnSuccess is executed. 

```

channel_->declareQueue("SomeName", AMQP::durable).OnSuccess([](const std::string &name, uint32_t messagecount, uint32_t consumercount){
    std::cout << "declared queue " << name << std::endl;
}).OnError([](const char* msg){ 
    std::cout << msg << std::endl;
});

```

Anyway I can install the OnSuccess callback and OnError callback before reportSuccess is called?

**Comment by EmielBruijntjes** [comment] 2021-08-03 12:16
I do not know what you mean. Do you have an example program in which neither the onSuccess nor the onError callback gets called?

**Comment by liushiqi9** [comment] 2021-08-04 03:26
Because my code are in company secured network, I cannot put it here, but I modified the example a little bit and it has the same effect.

In code below, declare_queue's OnSuccess and OnError both won't be called(appears aproximate every 20 times ). 

I did some debuging and found out that when both function are not called, the function call time sequence looks like this: 

(MainThread)declare_queue -> (MainThread)channel_impl:declareQueue -> (MainThread)channel_impl:send->(MainThread)tcpconnected: send -> (UVThread)tcpconnection:OnRecieve ->(UVThread) channelimpl:reportSuccess -> _(UVThread)oldestCallback is nullptr so return -> (MainThread) channelimpl:push ->  (MainThread) Now oldestCallback is nolonger nullptr.

Which will result on none of OnSuccess/OnError be called.

Using the slightly modified example: 
```
/**
 *  LibUV.cpp
 * 
 *  Test program to check AMQP functionality based on LibUV
 * 
 *  @author Emiel Bruijntjes <emiel.bruijntjes@copernica.com>
 *  @copyright 2015 - 2017 Copernica BV
 */

/**
 *  Dependencies
 */
#include <uv.h>
#include <amqpcpp.h>
#include <amqpcpp/libuv.h>
#include <thread>
#include <unistd.h>

/**
 *  Custom handler
 */
class MyHandler : public AMQP::LibUvHandler
{
private:
    /**
     *  Method that is called when a connection error occurs
     *  @param  connection
     *  @param  message
     */
    virtual void onError(AMQP::TcpConnection *connection, const char *message) override
    {
        std::cout << "error: " << message << std::endl;
    }

    /**
     *  Method that is called when the TCP connection ends up in a connected state
     *  @param  connection  The TCP connection
     */
    virtual void onConnected(AMQP::TcpConnection *connection) override 
    {
        std::cout << "connected" << std::endl;
    }
    
public:
    /**
     *  Constructor
     *  @param  uv_loop
     */
    MyHandler(uv_loop_t *loop) : AMQP::LibUvHandler(loop) {}

    /**
     *  Destructor
     */
    virtual ~MyHandler() = default;
};

void UVRunner(uv_loop_t* loop){
    uv_run(loop, UV_RUN_DEFAULT);
}

/**
 *  Main program
 *  @return int
 */
int main()
{
    // access to the event loop
    auto *loop = uv_default_loop();
    
    // handler for libev
    MyHandler handler(loop);
    
    // make a connection
    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost/"));
    auto uv_thread = new std::thread(&UVRunner, loop);
    
    // we need a channel too
    AMQP::TcpChannel channel(&connection);
    
    // Both function below might never be called.
    channel.declareQueue("SomeRandomQueue",AMQP::exclusive).onSuccess([&connection](const std::string &name, uint32_t messagecount, uint32_t consumercount) {
        // report the name of the temporary queue
        std::cout << "declared queue " << name << std::endl;
    }).onError([](const char* msg){
        std::cout << "declared queue error: " << msg << std::endl;
    });
    

    sleep(10);
    return 0;
}



```

**Comment by EmielBruijntjes** [comment] 2021-08-04 07:09
The objects (like channel, connection, etc) are not thread safe. You cannot call channel.declareQueue() from one thread, while the whole connection is managed in an other. I think your issue is caused by the fact that you are using threads. I am therefore closing this issue. If I am wrong, please provide a simpler example _without_ using threads.

**Closed by EmielBruijntjes** 2021-08-04 07:09 UTC

**Comment by rwols** [comment] 2021-08-04 07:18
Replace the `sleep(10)` by `uv_run(loop, UV_RUN_DEFAULT)` and remove `auto uv_thread = new std::thread(&UVRunner, loop);`

**Comment by liushiqi9** [comment] 2021-08-04 11:43
Than may I ask what is the correct way to declare_queue or publish data after uv_thread is running? 
Should I pass the data/command into uv_thread and run it from there?

**Comment by EmielBruijntjes** [comment] 2021-08-04 14:49
I don't see the point of starting a thread in the first place.

**Comment by liushiqi9** [comment] 2021-08-05 04:10
If main thread is running uv_run, how to publish some msg periodic?

**Comment by rwols** [comment] 2021-08-05 07:07
You can use a timer for that: http://docs.libuv.org/en/v1.x/timer.html

Set up and "start" the timer before calling `uv_run(loop, UV_RUN_DEFAULT)`
