### ISSUE TITLE
make fails :(

### ISSUE THREAD

**Issue by barabenka** [CopernicaMarketingSoftware/AMQP-CPP#117] opened 2017-02-24 06:28 UTC
Hi,

Make fails .... I would really appreciate if you could help. 

Thank you!

Siarhei

e3429fa0975:AMQP-CPP root# make
make -C src all
make[1]: Entering directory '/workspace/ws/AMQP-CPP/src'
g++ -Wall -c -I. -std=c++11 -MD -g -fpic -o receivedframe.o receivedframe.cpp
In file included from /usr/include/sys/types.h:72:0,
                 from includes.h:24,
                 from receivedframe.cpp:8:
connectionstartframe.h:124:13: error: expected unqualified-id before 'unsigned'
     uint8_t major() const
             ^
connectionstartframe.h:124:13: error: expected ')' before 'unsigned'
.....

 File /usr/include/sys/types.h:

++++ BEGIN CODE+++

#ifndef _SYS_TYPES_H
#ifdef __cplusplus
extern "C" {
#endif

#include <features.h>

#define __NEED_ino_t
#define __NEED_dev_t
#define __NEED_uid_t
#define __NEED_gid_t
#define __NEED_mode_t
#define __NEED_nlink_t
#define __NEED_off_t
#define __NEED_pid_t
#define __NEED_size_t
#define __NEED_ssize_t
#define __NEED_time_t
#define __NEED_timer_t
#define __NEED_clockid_t

#define __NEED_blkcnt_t
#define __NEED_fsblkcnt_t
#define __NEED_fsfilcnt_t

#define __NEED_id_t
#define __NEED_key_t
#define __NEED_clock_t
#define __NEED_suseconds_t
#define __NEED_blksize_t

#define __NEED_pthread_t
#define __NEED_pthread_attr_t
#define __NEED_pthread_mutexattr_t
#define __NEED_pthread_condattr_t
#define __NEED_pthread_rwlockattr_t
#define __NEED_pthread_barrierattr_t
#define __NEED_pthread_mutex_t
#define __NEED_pthread_cond_t
#define __NEED_pthread_rwlock_t
#define __NEED_pthread_barrier_t
#define __NEED_pthread_spinlock_t
#define __NEED_pthread_key_t
#define __NEED_pthread_once_t
#define __NEED_useconds_t

#if defined(_GNU_SOURCE) || defined(_BSD_SOURCE)
#define __NEED_int8_t
#define __NEED_int16_t
#define __NEED_int32_t
#define __NEED_int64_t
#define __NEED_u_int64_t
#define __NEED_register_t
#endif     <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< this is line 72

#include <bits/alltypes.h>

#if defined(_GNU_SOURCE) || defined(_BSD_SOURCE)
typedef unsigned char u_int8_t;
typedef unsigned short u_int16_t;
typedef unsigned u_int32_t;
typedef char *caddr_t;
typedef unsigned char u_char;
typedef unsigned short u_short, ushort;
typedef unsigned u_int, uint;
typedef unsigned long u_long, ulong;
typedef long long quad_t;
typedef unsigned long long u_quad_t;
#include <endian.h>
#include <sys/select.h>
#include <sys/sysmacros.h>
#endif

#if defined(_LARGEFILE64_SOURCE) || defined(_GNU_SOURCE)
#define blkcnt64_t blkcnt_t
#define fsblkcnt64_t fsblkcnt_t
#define fsfilcnt64_t fsfilcnt_t
#define ino64_t ino_t
#define off64_t off_t
#endif

#ifdef __cplusplus
}
#endif
#endif 

++++ END CODE+++

As an experiment, I changed (thinking that unit8_t is not defined) unit8_t >> int but the error persisted:
8e3429fa0975:AMQP-CPP root# make
make -C src all
make[1]: Entering directory '/workspace/ws/AMQP-CPP/src'
g++ -Wall -c -I. -std=c++11 -MD -g -fpic -o receivedframe.o receivedframe.cpp
In file included from /usr/include/sys/types.h:72:0,
                 from /usr/include/netinet/tcp.h:61,
                 from includes.h:29,
                 from receivedframe.cpp:8:
connectionstartframe.h:124:9: error: expected unqualified-id before 'unsigned'
     int major() const
         ^
connectionstartframe.h:124:9: error: expected ')' before 'unsigned'

I am running Linux in a Docker container:
8e3429fa0975:AMQP-CPP root# uname -or
4.4.38-boot2docker Linux

**Comment by fantastory** [comment] 2017-02-24 08:11
https://github.com/tommitytom/AMQP-CPP/commit/3a088734100fcca65261d1f891d781bdf47ac40b

**Comment by fantastory** [comment] 2017-02-24 11:24
@barabenka I have merged tommytom's fixes into my windows nuget build:
https://github.com/fantastory/AMQP-CPP
Would you mind to check if it builds on linux correctly?

**Comment by barabenka** [comment] 2017-02-24 16:30
Thank you fantastory, make in your branch succeeds.
Unfortunately, "make install" fails:

01b321ccefb8:AMQP-CPP root# make install
mkdir -p /usr/include/amqpcpp
mkdir -p /usr/lib
cp -f amqpcpp.h /usr/include
cp: can't stat 'amqpcpp.h': No such file or directory
make: *** [Makefile:29: install] Error 1

**Comment by fantastory** [comment] 2017-02-24 17:44
Arghhh. I moved all includes to single folder but i only "install" it on windows. 
I'll get some linux machine to fix things up. Hopefully tommitytom's branch would work for you.

**Comment by barabenka** [comment] 2017-02-28 06:13
Thank you, @fantastory. Tommitytom's branch does compile. However, I get the following error, when I include amqpcpp.h :(:

In file included from /usr/local/include/amqpcpp.h:39:0,
                 from /workspace/ws/ocl/test/include/testOcl.h:24,
                 from /workspace/ws/ocl/test/src/testOcl.cpp:22:
/usr/local/include/amqpcpp/outbuffer.h: In member function 'void AMQP::OutBuffer::add(uint16_t)':
/usr/local/include/amqpcpp/outbuffer.h:162:35: error: 'htobe16' was not declared in this scope
         uint16_t v = htobe16(value);
                                   ^
The htobe16 function is defined in endian.h. There are several endian.h files in the system. I don't know which one it is trying to use.... I will continue looking into it tomorrow.
Thanks again!

**Comment by fantastory** [comment] 2017-02-28 08:04
htobe16()? bigendian is the network one, you can safely use htons()

**Comment by barabenka** [comment] 2017-03-01 03:07
Thank you for your help. The call to htobe16 is in AMQP-CPP/inlcude/outbuffer.h, so, it is not my code. Removing the file AMQP-CPP/inlcude/endian.h  solved this issue. The system already has endian.h file which defined htobe16/32 functions. The file in AMQP-CPP/inlcude/endian.h was not compatible.

**Comment by fantastory** [comment] 2017-03-01 08:32
AMQP-CPP/inlcude/outbuffer.h is a system abstraction, it selects which system endian.h to include.

The file should be included as <amqpcpp\endian.h> rather than <endian.h>.

It seem that you are including it and (probably other files) from amqpcpp build library (where you downloaded it with git), rather than from its installation location (where make install puts them).
I guess, you have AMQP-CPP.git/inlcude/ in your build include path. I did the same and find it usefull when testing library. That is why I moved whole AMQP-CPP.git/inlcude/ to AMQP-CPP.git/inlcude/amqpcpp.

**Comment by bumbar1** [comment] 2017-03-02 13:48
I'm having trouble building (worked fine few ago when I built it on another machine),

cmake output:
```
$ cmake -G "Unix Makefiles"
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Warning (dev) at CMakeLists.txt:52 (set):
  Cannot set "AMQP-CPP_INCLUDE_PATH": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/git/AMQP-CPP
```

make output:
```
[  7%] Building CXX object CMakeFiles/amqp-cpp.dir/src/array.cpp.o
In file included from /home/user/git/AMQP-CPP/src/includes.h:70:0,
                 from /home/user/git/AMQP-CPP/src/array.cpp:7:
/home/user/git/AMQP-CPP/src/../include/channelimpl.h: In member function ‘void AMQP::ChannelImpl::onError(const ErrorCallback&)’:
/home/user/git/AMQP-CPP/src/../include/channelimpl.h:231:24: error: invalid use of incomplete type ‘class AMQP::ConnectionImpl’
         if (_connection->connected()) return callback("Channel is in an error state, but the connection is valid");
                        ^
In file included from /home/user/git/AMQP-CPP/src/includes.h:33:0,
                 from /home/user/git/AMQP-CPP/src/array.cpp:7:
/home/user/git/AMQP-CPP/src/../include/classes.h:30:7: error: forward declaration of ‘class AMQP::ConnectionImpl’
 class ConnectionImpl;
       ^
CMakeFiles/amqp-cpp.dir/build.make:54: recipe for target 'CMakeFiles/amqp-cpp.dir/src/array.cpp.o' failed
make[2]: *** [CMakeFiles/amqp-cpp.dir/src/array.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/amqp-cpp.dir/all' failed
make[1]: *** [CMakeFiles/amqp-cpp.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by EmielBruijntjes** [comment] 2017-03-04 18:27
This was caused by a wrong commit from me, and has now been solved.

**Closed by EmielBruijntjes** 2017-03-04 18:27 UTC
