### ISSUE TITLE
Problem: install TARGETS given unknown argument "EXPORT"

### ISSUE THREAD

**Issue by Puasonych** [CopernicaMarketingSoftware/AMQP-CPP#191] opened 2018-03-02 09:38 UTC
Good afternoon.
On the previous version this was not. :)

Maybe I did not understand something.

> cmake -DAMQP-CPP_BUILD_SHARED=ON ../amqpcpp
> -- The C compiler identification is GNU 4.8.3
> -- The CXX compiler identification is GNU 4.8.3
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at CMakeLists.txt:89 (install):
>   install TARGETS given unknown argument "EXPORT".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/dev/work/amqpcpp-build/CMakeFiles/CMakeOutput.log".

**Comment by surgura** [comment] 2018-03-02 10:10
@lion10243 @EmielBruijntjes This is caused by the recent addition for Hunter support. I don't know enough about CMake and Hunter to say if this hunter specific markdown or if it's part of CMake? Or maybe the required CMake version is incorrect?

**Comment by Puasonych** [comment] 2018-03-02 10:15
This error occurs in my CentOs7 (cmake 3.6.3)
I tested the assembly on Ubuntu (cmake 3.5.1) - there is no error.

**Comment by Puasonych** [comment] 2018-03-02 10:20
@surgura Just noticed that the error appears when the flag is specified **-DAMQP-CPP_BUILD_SHARED=ON**. :)

**Comment by surgura** [comment] 2018-03-02 10:21
Yes I just noticed that too. lubuntu, cmake 3.9.1 gets the error too. Only with shared.

**Comment by lion10243** [comment] 2018-03-02 10:43
It looks like the 'EXPORT' keyword was misplaced for install(TARGETS...) when AMQP-CPP_BUILD_SHARED was enabled. I'm testing this locally and will commit another change asap.

**Comment by Puasonych** [comment] 2018-03-02 10:44
@surgura @lion10243 I understood. Most likely an error while copying. :)
It is necessary to correct 89 and 90 line in the main CMakeLists.txt. 

Like this:
> if(AMQP-CPP_BUILD_SHARED)
>     # copy shared lib and its static counter part
>     install(TARGETS ${PROJECT_NAME} EXPORT ${PROJECT_NAME}Config
>             ARCHIVE DESTINATION lib
>             LIBRARY DESTINATION lib
>             RUNTIME DESTINATION lib
>     )

**Comment by lion10243** [comment] 2018-03-02 10:46
@Puasonych  @surgura @EmielBruijntjes  here is a fix PR  https://github.com/CopernicaMarketingSoftware/AMQP-CPP/pull/192

**Comment by surgura** [comment] 2018-03-02 10:55
@lion10243 Bit off-topic, but could you maybe quickly explain what the last 2 rows of the cmake file do?(106&107 install&export). The CMake docs are a bit..heavy on my brain :p

**Comment by lion10243** [comment] 2018-03-02 11:11
@surgura I'm not exactly a cmake power user myself... ;-)    lines 106-107 instruct cmake to install an exported "amqpcppConfig.cmake" file into the ${install_dir}/cmake target directory, which imports a 'amqpcpp' build target. It's mainly useful for the Hunter package manager, which can utillise the amqpcppConfig.cmake file so it knows about external projects.

**Comment by EmielBruijntjes** [comment] 2018-03-08 21:22
I merged the pull request. Is this issue now solved?

**Closed by EmielBruijntjes** 2018-03-08 21:22 UTC
